#!/bin/sh
die() { fmt=$1; shift; printf >&2 "%s: $fmt\n" "${0##*/}" "$@"; exit 1; }
[ "$#" -eq 4 ] || [ "$#" -eq 5 ] || { die 'Need 4 args: parent directory, showing name, ep start, ep end[, video source dir]'; }

dir=$1/$2
name=$2
ep_start=$3
ep_end=$4
seed_dir=$5

case $name in
    (*' '*) die 'No spaces allowed in showing name.\nThank Makefiles for that.';;
esac
[ "$ep_start" -le "$ep_end" ] || die 'Starting episode cannot be greater than ending episode.'

[ -d "$dir" ] || mkdir -- "$dir"
[ -d "$dir/1-orig" ] || mkdir -- "$dir/1-orig"

ep_list=
i=$ep_start
while [ "$i" -le "$ep_end" ]; do
    num=$(printf %02d "$i")
    ep=$name-$num
    ep_list="$ep_list $ep"

    if [ -n "$seed_dir" ]; then
        set -- "$seed_dir"/"$num"*
        if ! [ -f "$1" ]; then
            set -- "$seed_dir"/*[!0-9a-fA-F]"$num"[!0-9a-fA-F]*
        fi
        if [ -f "$1" ]; then
            ext=${1##*.}
            [ "${ext#*/}" = "$ext" ] || ext=mkv
            ln -s "$1" "$dir/1-orig/$ep.$ext"
        fi
    fi

    i=$((i+1))
done

{
cat << EOF
NAME           = $name
EPS            =$ep_list
EOF
cat << 'EOF'
EPS_DIR        = 1-orig
SUBS_DIR       = 2-subs
HARDSUBS_DIR   = 3-hardsubs
CUTS_DIR       = 4-cut
FINAL_DIR      = 5-final
FONT_DIR       = 0-fonts

FINAL_PRE      = final-uncompressed.mkv
FINAL_POST     = final.mkv

LOCAL_FONT_DIR = ~/.fonts/anime

HARDSUBS_RES   = 1280x720

ALL_EPS        = $(addprefix $(EPS_DIR)/, $(addsuffix .mkv, $(EPS)))
ALL_SUBS       = $(addprefix $(SUBS_DIR)/, $(addsuffix .ass, $(EPS)))
ALL_HARDSUBS   = $(addprefix $(HARDSUBS_DIR)/, $(addsuffix .mkv, $(EPS)))

TARGETS = subs hardsubs prep-cuts fonts

all: final

subs: $(ALL_SUBS)
hardsubs: $(ALL_HARDSUBS)

$(SUBS_DIR) $(HARDSUBS_DIR) $(CUTS_DIR) $(FINAL_DIR) $(FONT_DIR):
	mkdir -- $@

fonts: $(FONT_DIR)
	cd -- $(FONT_DIR) && for f in $(addprefix ../, $(ALL_EPS)); do ffmpeg -dump_attachment:t '' -i "$$f" -y -nostdin; done || :
	cd -- $(FONT_DIR) && for f in ./*; do cp -v -- "$$f" $(LOCAL_FONT_DIR)/; done

$(SUBS_DIR)/%.ass: $(EPS_DIR)/%.mkv | $(SUBS_DIR)
	ffmpeg -hide_banner -i $< -vn -an -c:s copy -y -nostdin $@
	dos2unix $@

$(HARDSUBS_DIR)/%.mkv: $(EPS_DIR)/%.mkv $(SUBS_DIR)/%.ass | $(HARDSUBS_DIR)
	ff-hardsub $+ $@ $(HARDSUBS_RES)

CUTS = NO_CUTS_DEFINED_PLEASE_CREATE_cuts.mk
-include cuts.mk

cuts: $(CUTS)

$(FINAL_DIR)/$(FINAL_PRE): $(CUTS) | $(FINAL_DIR)
	mkvmerge --generate-chapters when-appending --generate-chapters-name-template '<FILE_NAME>' -o $@ '[' $^ ']'; [ "$$?" -le 1 ]

$(FINAL_DIR)/$(FINAL_POST): $(FINAL_DIR)/$(FINAL_PRE)
	ff-lossy-h264 $< $@

final: $(FINAL_DIR)/$(FINAL_POST)

.PHONY: all subs hardsubs fonts cuts final
EOF
} > "$dir/Makefile"
